### ISSUE TITLE
How can I catch connection errors?

### ISSUE THREAD

**Issue by McOmghall** [johndgiese/angular-hyper-resource#2]
I'm currently working on the client-side code for my services without connection to them, and I have a line like

```
 new ResourceContext(HalResource).get(myRoot).$get()
```

which throws me an `response.headers is not a function` error. What's the correct way to handle these, a `.then` error handler?

**Comment by johndgiese** [comment]
Can you paste a stack trace?

**Comment by McOmghall** [comment]
Here you are. I anonymized file names but everything (including your library) is on the same file using `browserify` and `uglify` to minimize.

```
16:59:14.186 Object { data: null, status: -1, headers: headersGetter/<(), config: Object, statusText: "", error: Object }1 xxx.js:14330:18
consoleLog/<() xxx.js:14330
$ExceptionHandlerProvider/this.$get</<() xxx.js:11059
processQueue() xxx.js:16654
scheduleProcessQueue/<() xxx.js:16662
$RootScopeProvider/this.$get</Scope.prototype.$eval() xxx.js:17914
$RootScopeProvider/this.$get</Scope.prototype.$digest() xxx.js:17730
$RootScopeProvider/this.$get</Scope.prototype.$apply() xxx.js:18022
done() xxx.js:12360
completeRequest() xxx.js:12558
createHttpBackend/</requestError() xxx.js:12509
```

**Comment by johndgiese** [comment]
Hmm, it is not clear to me that this has anything to do `angular-hyper-resource` from the stack trace.  Can you post more context from the file it is used in maybe?

**Comment by McOmghall** [comment]
I don't think there's any error with the library, I was just asking what's the Best Practice way of dealing with errors coming from the `$http` backend.

**Comment by johndgiese** [comment]
Oh I see---yes, as you say, use `.then`.
